### ISSUE TITLE
Problem with not valid utf-8 data from ssdb

### ISSUE THREAD

**Issue by bdfy** [hit9/ssdb.py#6]
simple "bad" ruby script:

require 'zlib'.
require 'date'.
require 'redis'
require 'cgi'
require 'json'
require 'uri'

@redis = Redis.new(:host => '127.0.0.1', :port => 2380,:thread_safe => true, :db => 0)
@redis.set 'test', " \xD0\xAE\xD0\xB7\xD0\xB5\xD1\x80\xD0\xB0\xD0\xB3\xD0\xB5\xD0\xBD\xD1\x82 64\xD1\x8"
@redis.set 'test1', " \xD0\xAE\xD0\xB7\xD0\xB5\xD1\x80\xD0\xB0\xD0\xB3\xD0\xB5\xD0\xBD\xD1\x82 64\xD1\x8".encode('UTF-8', :invalid => :replace, :undef => :replace)

python script:
import ssdb
db = ssdb.Client(host="localhost", port=2380)

    print ( db.get("test1") )
    try:
        print ( db.get("test") )
    except:
        db.conn.commands = []
    print ( db.get("test1") )
    print ( db.get("test1") )

result, exception, despite try/except:
Traceback (most recent call last):
  File "./1.py", line 14, in <module>
    print ( db.get("test1") )
  File "/usr/lib/python3.4/site-packages/ssdb.py", line 199, in method
    return self.conn.request()[0]
  File "/usr/lib/python3.4/site-packages/ssdb.py", line 170, in request
    self.parser.feed(string(buf))
  File "/usr/lib/python3.4/site-packages/ssdb.py", line 21, in <lambda>
    string = lambda binary: binary.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 30: invalid continuation byte

  db.conn.commands = [] solve this problem

**Comment by hit9** [comment]
Hi, I no more maintains this project, pull requests are welcome!

**Comment by bdfy** [comment]
ok, stupid patch ( clear self.commands before raise Exception )

[www.txt](https://github.com/hit9/ssdb.py/files/230260/www.txt)

**Comment by hit9** [comment]
@bdfy Thanks, but could you open a pull request instead?
